# Builds the package and runs all tests.
name: CI

on:
  push:
    branches-ignore:
      - master
      - develop
      - release-*

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.ref }}-ci
        cancel-in-progress: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install modules
        run: npm ci --no-audit --no-fund

      - name: Verify attestations
        run: npm audit signatures

      - name: Lint
        run: npm run lint

      - name: Build package
        run: npm run build-package

      - name: Run unit tests
        run: |
            npx http-server -s &
            npm run test

